# Generated by Django 4.1.3 on 2022-11-27 15:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/avatar/default/user-img.png', upload_to=accounts.models.content_file_name),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'مدیر'), ('2', 'فروشنده'), ('3', 'نویسنده'), ('4', 'امور مالی'), ('5', 'مسئول سفارشات'), ('6', 'کارمند'), ('7', 'سئو'), ('8', 'مشترک')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
