# Generated by Django 4.1.3 on 2022-11-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_about_user_avatar_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'مدیر'), ('2', 'فروشنده'), ('3', 'نویسنده'), ('4', 'حسابداری'), ('5', 'مسئول سفارشات'), ('6', 'کارمند'), ('7', 'سئو'), ('8', 'مشترک')], max_length=1, null=True),
        ),
    ]
